#!/bin/bash
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=128
#SBATCH --cpus-per-task=1
#SBATCH --partition=cpu
#SBATCH --account=mzu-delta-cpu
#SBATCH --job-name=myjobtest
#SBATCH --time=00:20:00      # hh:mm:ss for the job
#SBATCH --constraint="scratch"

echo "job is starting p, process cnt per node=4, node=2 on `hostname`"
mpirun -np 1024 mpi_io /scratch/mzu/yanniz3/CkIOBenchmark/TEST_FILES/file128gb_2
